version: "3.3"

services:
  app:
    image: corail-upload-system-app:latest
    env_file: .env
    environment:
      - DB_PATH=/data/db.sqlite3
    ports:
      - "8283:80"
    volumes:
      - sqlite_data:/data
      - media_data:/app/media
    restart: unless-stopped

volumes:
  sqlite_data:
  media_data:
