# Generated by Django 5.2.8 on 2026-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_uploadimagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='diving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
