# Generated by Django 5.2.8 on 2026-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_profile_divesite_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='depth_category',
            field=models.CharField(blank=True, choices=[('0_5m', '0 – 5 m'), ('5m', '5 m'), ('10m', '10 m'), ('gt_10m', '> 10 m'), ('custom', 'Free entry')], max_length=10),
        ),
    ]
