# Generated by Django 5.2.8 on 2026-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_uploadimagemodel_depth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='country',
            field=models.CharField(blank=True, default='Indonesia', max_length=100),
        ),
        migrations.AddField(
            model_name='divesite',
            name='region',
            field=models.CharField(blank=True, help_text='Region / Island / City, e.g., Raja Ampat / Misool - Marine Protected Area', max_length=255),
        ),
    ]
