# Generated by Django 5.2.8 on 2026-07-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_seed_dive_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='divesite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
