# Generated by Django 5.2.8 on 2026-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_uploadimagemodel_diving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='dive_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10),
        ),
    ]
