# Generated by Django 5.2.8 on 2026-09-04 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_replace_placeholder_dive_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
